package main

// func main() {
// 	println("Hello, World!")

// 	//var card string = "Ace of Spades"
// 	card := "Ace of Spades"   //initialization
// 	card = "Five of Diamonds" //reassignment of value
// 	fmt.Println(card)
// }

//   ------

// func main() {
// 	card := newCard()

// 	fmt.Println(card)
// }

// func newCard() string {
// 	return "Five of Diamonds"
// }

// func main() {
// 	cards := deck{"Ace of Diamonds", newCard()}
// 	cards = append(cards, "Six of Spades")

// 	// for i, card := range cards {
// 	// 	fmt.Println(i, card)
// 	// }

// 	cards.print()
// }

// func newCard() string {
// 	return "Five of Diamonds"
// }

func main() {
	// cards := newDeck()
	// //cards.print()
	// hand, remainingCards := deal(cards, 5)
	// hand.print()
	// remainingCards.print()
	// greeting := "Hi there!"
	// fmt.Println([]byte(greeting))

	//cards := newDeck()
	//fmt.Println(cards.toString())
	//cards.saveTofile("my_cards")
	//It will create a file named "my_cards" in the current directory and write the string representation of the deck to that file. The file will contain the list of cards separated by commas, as generated by the toString() method of the deck type.

	cards := newDeckFromFile("my_cards")
	cards.print()

}
